/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	miniooperator3xpl0it3rcnv1alpha1 "github.com/3Xpl0it3r/minio-operator/pkg/apis/miniooperator.3xpl0it3r.cn/v1alpha1"
	versioned "github.com/3Xpl0it3r/minio-operator/pkg/client/clientset/versioned"
	internalinterfaces "github.com/3Xpl0it3r/minio-operator/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/3Xpl0it3r/minio-operator/pkg/client/listers/miniooperator.3xpl0it3r.cn/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// MinioInformer provides access to a shared informer and lister for
// Minios.
type MinioInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.MinioLister
}

type minioInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewMinioInformer constructs a new informer for Minio type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewMinioInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredMinioInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredMinioInformer constructs a new informer for Minio type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredMinioInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.MiniooperatorV1alpha1().Minios(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.MiniooperatorV1alpha1().Minios(namespace).Watch(context.TODO(), options)
			},
		},
		&miniooperator3xpl0it3rcnv1alpha1.Minio{},
		resyncPeriod,
		indexers,
	)
}

func (f *minioInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredMinioInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *minioInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&miniooperator3xpl0it3rcnv1alpha1.Minio{}, f.defaultInformer)
}

func (f *minioInformer) Lister() v1alpha1.MinioLister {
	return v1alpha1.NewMinioLister(f.Informer().GetIndexer())
}
