apiVersion:  miniooperator.3xpl0it3r.cn/v1alpha1
kind: Minio
metadata:
  name: minio
spec:
  replicas: 4
  image: "registry.bizsaas.net/quay.io/minio"
  # image: "minio/minio"
  hostpath: "/data/fake_minio"
  buckets: ["btest1", "btest2", "btest3"]
  credential:
    access_key: "root123"
    secret_key: "adminadmin"
