apiVersion: v1
kind: ServiceAccount
metadata:
  name: clickpaas-sa
  namespace: default

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: clickpaas
rules:
  - apiGroups: [""]
    resources: [ "pods", "services"]
    verbs: ["get", "delete", "update", "list", "watch", "create"]
  - apiGroups: [""]
    resources: [ "nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: [ "customresourcedefinitions"]
    verbs: ["get", "delete", "create"]
  - apiGroups: ["miniooperator.3xpl0it3r.cn"]
    resources: [ "minios"]
    verbs: ["get", "list", "watch", "delete", "update", "create"]
  - apiGroups: ["miniooperator.3xpl0it3r.cn"]
    resources: [ "minios/status"]
    verbs: ["get", "update",]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: clickpaas
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: clickpaas
subjects:
  - kind: ServiceAccount
    name: clickpaas-sa
    namespace: default
--- 
apiVersion:  apps/v1
kind: Deployment
metadata:
  labels:
    app: clickpaas-operator-minio
  name: clickpaas-operator-minio
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clickpaas-operator-minio
  template:
    metadata:
      labels:
        app: clickpaas-operator-minio
    spec:
      containers:
      - name: clickpaas-operator-minio
        image: registry.bizsaas.net/operator/minio-operator:2022-10-11-v1
        imagePullPolicy: IfNotPresent
        resources: {}
      restartPolicy: Always
      serviceAccount: clickpaas-sa
