/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/3Xpl0it3r/minio-operator/pkg/apis/miniooperator.3xpl0it3r.cn/v1alpha1"
	scheme "github.com/3Xpl0it3r/minio-operator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// MiniosGetter has a method to return a MinioInterface.
// A group's client should implement this interface.
type MiniosGetter interface {
	Minios(namespace string) MinioInterface
}

// MinioInterface has methods to work with Minio resources.
type MinioInterface interface {
	Create(ctx context.Context, minio *v1alpha1.Minio, opts v1.CreateOptions) (*v1alpha1.Minio, error)
	Update(ctx context.Context, minio *v1alpha1.Minio, opts v1.UpdateOptions) (*v1alpha1.Minio, error)
	UpdateStatus(ctx context.Context, minio *v1alpha1.Minio, opts v1.UpdateOptions) (*v1alpha1.Minio, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.Minio, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.MinioList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Minio, err error)
	MinioExpansion
}

// minios implements MinioInterface
type minios struct {
	client rest.Interface
	ns     string
}

// newMinios returns a Minios
func newMinios(c *MiniooperatorV1alpha1Client, namespace string) *minios {
	return &minios{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the minio, and returns the corresponding minio object, and an error if there is any.
func (c *minios) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Minio, err error) {
	result = &v1alpha1.Minio{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("minios").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Minios that match those selectors.
func (c *minios) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.MinioList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.MinioList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("minios").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested minios.
func (c *minios) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("minios").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a minio and creates it.  Returns the server's representation of the minio, and an error, if there is any.
func (c *minios) Create(ctx context.Context, minio *v1alpha1.Minio, opts v1.CreateOptions) (result *v1alpha1.Minio, err error) {
	result = &v1alpha1.Minio{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("minios").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(minio).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a minio and updates it. Returns the server's representation of the minio, and an error, if there is any.
func (c *minios) Update(ctx context.Context, minio *v1alpha1.Minio, opts v1.UpdateOptions) (result *v1alpha1.Minio, err error) {
	result = &v1alpha1.Minio{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("minios").
		Name(minio.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(minio).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *minios) UpdateStatus(ctx context.Context, minio *v1alpha1.Minio, opts v1.UpdateOptions) (result *v1alpha1.Minio, err error) {
	result = &v1alpha1.Minio{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("minios").
		Name(minio.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(minio).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the minio and deletes it. Returns an error if one occurs.
func (c *minios) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("minios").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *minios) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("minios").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched minio.
func (c *minios) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Minio, err error) {
	result = &v1alpha1.Minio{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("minios").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
